#!/usr/bin/env python3
import os, sys

VENV = os.path.join(os.path.dirname(__file__), ".venv")
PYTHON = os.path.join(VENV, "bin", "python3")
if not os.path.exists(PYTHON):
    PYTHON = os.path.join(VENV, "bin", "python")

if os.path.exists(PYTHON):
    os.execv(PYTHON, [PYTHON, os.path.join(os.path.dirname(__file__), "app.py")] + sys.argv[1:])
else:
    os.execv(sys.executable, [sys.executable, os.path.join(os.path.dirname(__file__), "app.py")] + sys.argv[1:])
